version: "2.2"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  bad-bank-backend:
    depends_on:
      - mongodb_container
    build: .
    environment:
      - MONGO_CONNECTION_STRING=mongodb://root:rootpassword@mongodb_container
    ports:
      - 443:443

volumes:
  mongodb_data_container:
